# Generated by Django 4.1.9 on 2023-05-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0026_ekstremifunkcije_kvadratnaizracunajnicle_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EkstremiFunkcije',
            new_name='EkstremiPolinoma',
        ),
    ]
